name: "automate-update"

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger via GitHub UI

jobs:
  automate-update:
    runs-on: ubuntu-latest

    steps:
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Install Dependencies"
        run: npm install

      - name: "Run the App"
        run: npm run dev
